// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'autogenerated', dirName: 'docs'
    },
    {
      type: 'link',
      label: 'Civo API documentation',
      href: 'https://www.civo.com/api',
    }
  ],
};

module.exports = sidebars;
