name: Civo docs deployment

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checout
        uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_SHA}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: civobot/civo-docusaurus:${{ steps.vars.outputs.tag }}
      - name: Generate kubeconfig 
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBECONFIG }} | base64 --decode > ${HOME}/.kube/config
      - name: Switch to deployment cluster
        run: kubectl config use-context ${{ secrets.CLUSTER_NAME }}
      - name: update and deploy to k8s 
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            .github/workflows/deploy/deployment.yaml
            .github/workflows/deploy/service.yaml
          replacement-method: defined
        env:
          IMAGE_TAG: ${{ github.sha }}